GET http://localhost:3000/items

###

GET http://localhost:3000/items/68aafc52966de7ec30aade4f

###

POST http://localhost:3000/items
Content-Type: application/json

{
  "name": "아이폰",
  "description": "아이폰 17",
  "price": 900000,
  "tags": ["전자기기", "스마트폰"]
}

###

PATCH  http://localhost:3000/items/68aafc52966de7ec30aade4f
Content-Type: application/json

{
  "description": "로봇 청소기 제품 설명입니다."
}


###
DELETE  http://localhost:3000/items/68ab13c03216e2b18c214749