import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./(components)/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pretender = localFont({
  src: [
    {
      path: "../../public/fonts/PretendardVariable.woff2",
      display: "swap",
      weight: "45 920",
    },
  ],
  variable: "--font-pretendard",
});

const rokaf = localFont({
  src: [
    {
      path: "../../public/fonts/ROKAF-Sans-Bold.ttf",
      weight: "700",
      style: "bold",
    },
    {
      path: "../../public/fonts/ROKAF-Sans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-rokaf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`antialiased ${rokaf.variable} ${pretender.variable}`}
    >
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
